module PageFactory.Engine.Assets
  ( appScript
  , css
  ) where

-- Inline CSS and browser-side fragment navigation script.

import Data.List (intercalate)

css :: String
css =
  intercalate
    "\n"
    [ ":root { --runtime-accent: #35535b; color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; color: #171b22; background: #f6f7f5; }"
    , "* { box-sizing: border-box; }"
    , "html { min-height: 100%; }"
    , "body { margin: 0; min-height: 100vh; min-height: 100dvh; background: #f6f7f5; }"
    , "a { color: inherit; }"
    , ".app-container { min-height: 100vh; min-height: 100dvh; }"
    , ".app-shell { display: grid; grid-template-columns: minmax(360px, 440px) minmax(0, 1fr); align-items: stretch; gap: 0; width: 100%; min-height: 100vh; min-height: 100dvh; margin: 0; padding: 0; transition: grid-template-columns 180ms ease; }"
    , ".app-container[data-sidebar-collapsed=\"true\"] .app-shell { grid-template-columns: 18px minmax(0, 1fr); }"
    , ".content-shell { min-width: 0; }"
    , ".topbar { display: flex; align-items: center; justify-content: space-between; min-height: 56px; padding: 0 32px; border-bottom: 1px solid rgba(23, 27, 34, 0.1); background: rgba(255, 255, 255, 0.86); backdrop-filter: blur(12px); }"
    , ".topbar span { color: #69737d; font-size: 14px; }"
    , ".brand { color: var(--runtime-accent); font-weight: 800; text-decoration: none; }"
    , ".nav-meta { display: inline-flex; align-items: center; gap: 10px; min-width: 160px; justify-content: flex-end; }"
    , ".renderer-label { transition: color 160ms ease; }"
    , ".nav-spinner { width: 16px; height: 16px; border: 2px solid rgba(53, 83, 91, 0.18); border-top-color: var(--runtime-accent); border-radius: 999px; opacity: 0; transform: scale(0.82); transition: opacity 160ms ease, transform 160ms ease; }"
    , ".app-container[data-loading=\"true\"] .nav-spinner { opacity: 1; transform: scale(1); animation: spin 900ms linear infinite; }"
    , ".app-container[data-loading=\"true\"] .renderer-label { color: var(--runtime-accent); }"
    , "@keyframes spin { to { transform: scale(1) rotate(360deg); } }"
    , "[data-render-part], [data-fragment-slot] { transition: opacity 70ms ease, filter 80ms ease, transform 80ms ease; }"
    , ".fragment-fade-out { opacity: 0; filter: blur(2px); transform: translateY(1px); pointer-events: none; }"
    , ".fragment-fade-in { opacity: 0; filter: blur(2px); transform: translateY(-1px); }"
    , ".fragment-fade-ready { opacity: 1; filter: blur(0); transform: translateY(0) scale(1); }"
    , "@media (prefers-reduced-motion: reduce) { [data-render-part], [data-fragment-slot] { transition: none; } .fragment-fade-out, .fragment-fade-in { opacity: 1; filter: none; transform: none; } }"
    , ".shell { width: min(980px, calc(100% - 64px)); margin: 0 auto; padding: 44px 0; }"
    , ".intro, .profile { padding: 28px 0 32px; }"
    , ".eyebrow { margin: 0 0 10px; color: #6f5d3f; font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0; }"
    , "h1 { margin: 0 0 16px; font-size: clamp(34px, 6vw, 62px); line-height: 1; letter-spacing: 0; }"
    , "p { max-width: 680px; font-size: 18px; line-height: 1.6; }"
    , ".demo-links { display: grid; grid-template-columns: repeat(auto-fit, minmax(168px, 1fr)); gap: 8px; max-width: 860px; margin-top: 24px; }"
    , ".demo-link { display: grid; gap: 3px; min-height: 62px; padding: 11px 12px; border: 1px solid rgba(23, 27, 34, 0.12); border-radius: 8px; background: rgba(255, 255, 255, 0.74); text-decoration: none; }"
    , ".demo-link:hover { border-color: color-mix(in srgb, var(--runtime-accent) 48%, #cfd8d7); background: rgba(255, 255, 255, 0.92); }"
    , ".demo-link strong { color: var(--runtime-accent); font-size: 14px; }"
    , ".demo-link span { color: #69737d; font-size: 12px; line-height: 1.35; }"
    , ".story-shell { width: min(1180px, calc(100% - 48px)); }"
    , ".story-hero { padding-bottom: 16px; }"
    , ".story-tabs { margin-top: 18px; }"
    , ".story-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 10px; }"
    , ".story-card { display: grid; gap: 6px; min-height: 112px; padding: 14px; border: 1px solid rgba(23, 27, 34, 0.1); border-radius: 8px; background: rgba(255, 255, 255, 0.78); text-decoration: none; }"
    , ".story-card:hover { border-color: color-mix(in srgb, var(--runtime-accent) 36%, #cfd8d7); background: #ffffff; }"
    , ".story-card strong { color: #171b22; font-size: 22px; line-height: 1.1; }"
    , ".story-card span { color: #69737d; font-size: 13px; line-height: 1.35; }"
    , ".story-frame { display: grid; gap: 10px; margin: 0 0 18px; }"
    , ".story-frame > header { display: flex; align-items: center; min-height: 34px; border-bottom: 1px solid rgba(23, 27, 34, 0.1); }"
    , ".story-frame > header h2 { margin: 0; color: #69737d; font-size: 13px; font-weight: 900; text-transform: uppercase; }"
    , ".story-stage { min-width: 0; padding: 14px; border: 1px solid rgba(23, 27, 34, 0.1); border-radius: 8px; background: rgba(255, 255, 255, 0.58); overflow: auto; }"
    , ".story-stage .shell { width: 100%; padding: 0; }"
    , ".story-stage .profile { padding-top: 0; }"
    , ".story-stage .sandbox-doc-shell { width: 100%; padding: 0; }"
    , ".story-stage .sandbox-doc-toolbar { position: static; }"
    , ".story-stage .sandbox-side-panel { position: static; }"
    , ".story-stage .ticker-detail-panel { min-height: 240px; }"
    , ".story-agent-panel { max-width: 460px; margin: 0; }"
    , ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; }"
    , ".card { display: grid; gap: 8px; min-height: 164px; padding: 18px; border: 1px solid #cfd8d7; border-radius: 8px; background: rgba(255, 255, 255, 0.72); text-decoration: none; box-shadow: 0 14px 40px rgba(38, 48, 63, 0.08); }"
    , ".card:hover { border-color: #78908f; transform: translateY(-1px); }"
    , ".card-id { color: #69737d; font-size: 13px; }"
    , ".card strong { font-size: 24px; }"
    , ".card span { overflow-wrap: anywhere; }"
    , ".trading-hero { padding-bottom: 18px; }"
    , ".trading-tabs { margin-top: 4px; }"
    , ".trading-panel { margin-top: 10px; }"
    , ".trading-controls { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 14px; }"
    , ".trading-controls input { min-width: 120px; flex: 1 1 160px; min-height: 36px; padding: 7px 10px; border: 1px solid rgba(23, 27, 34, 0.14); border-radius: 7px; background: #ffffff; color: #171b22; font: inherit; font-size: 14px; outline: none; }"
    , ".trading-controls button, .ticker-remove { min-height: 34px; padding: 0 10px; border: 0; border-radius: 7px; background: rgba(53, 83, 91, 0.1); color: var(--runtime-accent); font: inherit; font-size: 13px; font-weight: 800; cursor: pointer; }"
    , ".trading-controls button:hover, .ticker-remove:hover { background: rgba(53, 83, 91, 0.16); }"
    , ".ticker-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; }"
    , ".ticker-card { display: grid; gap: 6px; min-height: 132px; padding: 14px; border: 1px solid rgba(23, 27, 34, 0.1); border-radius: 8px; background: rgba(255, 255, 255, 0.72); }"
    , ".ticker-card-link { display: grid; gap: 6px; color: inherit; text-decoration: none; }"
    , ".ticker-card-link:hover strong { color: var(--runtime-accent); }"
    , ".ticker-card strong { color: #171b22; font-size: 28px; letter-spacing: 0; }"
    , ".ticker-card span:not(.card-id) { color: var(--runtime-accent); font-size: 18px; font-weight: 800; }"
    , ".ticker-detail-panel { min-height: 340px; }"
    , ".ticker-detail-card { display: grid; gap: 14px; }"
    , ".ticker-detail-card strong { font-size: clamp(56px, 12vw, 128px); line-height: 0.9; letter-spacing: 0; }"
    , ".ticker-detail-price { color: var(--runtime-accent); font-size: clamp(34px, 7vw, 76px); font-weight: 900; line-height: 1; }"
    , ".trading-error { display: grid; gap: 8px; padding: 16px; border: 1px solid rgba(122, 31, 42, 0.22); border-radius: 8px; background: #fff5f6; color: #7a1f2a; }"
    , ".trading-error strong { font-size: 18px; }"
    , ".trading-error p { margin: 0; max-width: none; color: inherit; font-size: 14px; line-height: 1.45; }"
    , ".sandbox-hero { padding-bottom: 18px; }"
    , ".sandbox-doc-shell { width: min(1220px, calc(100% - 48px)); padding: 28px 0; }"
    , ".sandbox-create, .sandbox-editor { display: grid; gap: 8px; margin-bottom: 14px; }"
    , ".sandbox-create { grid-template-columns: minmax(120px, 0.45fr) minmax(160px, 0.55fr) auto; align-items: start; }"
    , ".sandbox-create textarea { grid-column: 1 / -1; }"
    , ".sandbox-create input, .sandbox-create textarea, .sandbox-editor input, .sandbox-editor textarea { width: 100%; padding: 9px 10px; border: 1px solid rgba(23, 27, 34, 0.14); border-radius: 7px; background: #ffffff; color: #171b22; font: inherit; font-size: 14px; outline: none; }"
    , ".sandbox-create button, .sandbox-editor button { min-height: 36px; padding: 0 12px; border: 0; border-radius: 7px; background: var(--runtime-accent); color: #ffffff; font: inherit; font-size: 13px; font-weight: 800; cursor: pointer; }"
    , ".sandbox-create button { grid-column: 1 / -1; justify-self: start; min-width: 132px; }"
    , ".sandbox-doc-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 10px; }"
    , ".sandbox-doc-card { display: grid; grid-template-rows: auto 1fr auto; gap: 10px; min-height: 128px; padding: 14px; border: 1px solid rgba(23, 27, 34, 0.09); border-radius: 8px; background: rgba(255, 255, 255, 0.78); text-decoration: none; }"
    , ".sandbox-doc-card:hover { border-color: color-mix(in srgb, var(--runtime-accent) 34%, rgba(23, 27, 34, 0.1)); background: #ffffff; }"
    , ".sandbox-doc-card strong { align-self: center; color: #171b22; font-size: 20px; line-height: 1.15; overflow-wrap: anywhere; }"
    , ".sandbox-doc-meta { display: flex; align-items: center; justify-content: space-between; gap: 10px; min-width: 0; }"
    , ".sandbox-doc-icon { flex: 0 0 auto; display: inline-flex; align-items: center; justify-content: center; width: 30px; height: 24px; border-radius: 6px; background: rgba(53, 83, 91, 0.08); color: var(--runtime-accent); font-size: 11px; font-weight: 900; text-transform: uppercase; }"
    , ".sandbox-doc-meta .card-id { min-width: 0; margin-left: auto; overflow: hidden; color: #69737d; font-size: 12px; font-weight: 700; text-overflow: ellipsis; white-space: nowrap; }"
    , ".sandbox-doc-updated { color: #69737d; font-size: 12px; line-height: 1.25; }"
    , ".sandbox-document { min-width: 0; }"
    , ".sandbox-editor { gap: 14px; margin: 0; }"
    , ".sandbox-doc-toolbar { position: sticky; top: 56px; z-index: 1; display: grid; grid-template-columns: auto minmax(180px, 1fr) auto auto; align-items: center; gap: 10px; min-height: 54px; padding: 8px; border: 1px solid rgba(23, 27, 34, 0.1); border-radius: 8px; background: rgba(255, 255, 255, 0.9); backdrop-filter: blur(12px); }"
    , ".sandbox-doc-toolbar .back { margin: 0; padding: 0 8px; white-space: nowrap; }"
    , ".sandbox-title-input { min-height: 38px; border-color: transparent !important; background: transparent !important; color: #171b22 !important; font-size: 22px !important; font-weight: 850 !important; }"
    , ".sandbox-doc-toolbar .sandbox-doc-updated { white-space: nowrap; }"
    , ".sandbox-doc-toolbar button { min-width: 84px; }"
    , ".sandbox-workspace { display: grid; grid-template-columns: minmax(420px, 0.72fr) minmax(280px, 0.28fr); gap: 18px; align-items: start; }"
    , ".sandbox-page-wrap { display: grid; min-height: 760px; padding: 54px 64px; border: 1px solid rgba(23, 27, 34, 0.12); border-radius: 8px; background: #ffffff; box-shadow: 0 18px 48px rgba(38, 48, 63, 0.08); }"
    , ".sandbox-page { min-height: 650px; padding: 0 !important; border: 0 !important; border-radius: 0 !important; resize: vertical; background: #ffffff !important; color: #171b22 !important; font: 17px/1.68 Georgia, 'Times New Roman', serif !important; }"
    , ".sandbox-side-panel { position: sticky; top: 124px; min-width: 0; }"
    , ".sandbox-side-card { display: grid; gap: 8px; padding: 14px; border: 1px solid rgba(23, 27, 34, 0.08); border-radius: 8px; background: rgba(255, 255, 255, 0.66); }"
    , ".sandbox-side-card h2 { margin: 0 0 4px; font-size: 22px; line-height: 1.1; overflow-wrap: anywhere; }"
    , ".sandbox-rendered { display: grid; gap: 9px; color: #262b33; }"
    , ".sandbox-rendered h2, .sandbox-rendered h3, .sandbox-rendered h4, .sandbox-rendered p, .sandbox-rendered ul { margin: 0; }"
    , ".sandbox-rendered h2 { font-size: 22px; line-height: 1.15; }"
    , ".sandbox-rendered h3 { font-size: 18px; line-height: 1.2; }"
    , ".sandbox-rendered h4 { font-size: 15px; line-height: 1.25; }"
    , ".sandbox-rendered p, .sandbox-rendered li { font-size: 14px; line-height: 1.5; }"
    , ".sandbox-rendered ul { padding-left: 18px; }"
    , ".status { align-self: end; width: fit-content; padding: 5px 9px; border-radius: 999px; font-size: 13px; font-style: normal; font-weight: 700; }"
    , ".ok { color: #145232; background: #dff4e8; }"
    , ".debt { color: #7a1f2a; background: #ffe1e5; }"
    , ".back { display: inline-flex; margin-bottom: 26px; color: var(--runtime-accent); font-weight: 700; text-decoration: none; }"
    , ".facts { display: grid; gap: 12px; max-width: 620px; margin: 22px 0 0; }"
    , ".facts div { display: grid; grid-template-columns: 150px 1fr; gap: 16px; padding: 16px 0; border-top: 1px solid #cfd8d7; }"
    , "dt { color: #69737d; }"
    , "dd { margin: 0; font-weight: 700; overflow-wrap: anywhere; }"
    , ".client-workspace { margin-top: 18px; border-top: 1px solid #cfd8d7; padding-top: 18px; }"
    , ".tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 14px; }"
    , ".tab { min-height: 36px; display: inline-flex; align-items: center; padding: 0 13px; border: 1px solid #cfd8d7; border-radius: 999px; background: rgba(255, 255, 255, 0.62); color: var(--runtime-accent); font-size: 14px; font-weight: 700; text-decoration: none; }"
    , ".tab.active { border-color: var(--runtime-accent); background: var(--runtime-accent); color: #ffffff; }"
    , ".panel { min-height: 180px; padding: 18px; border: 1px solid #cfd8d7; border-radius: 8px; background: rgba(255, 255, 255, 0.62); }"
    , ".panel h2 { margin: 0 0 10px; font-size: 28px; letter-spacing: 0; }"
    , ".metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-top: 16px; }"
    , ".metric { display: grid; gap: 4px; padding: 14px; border-radius: 8px; background: #f7f7f2; }"
    , ".metric span, .invoice-list span { color: #69737d; font-size: 14px; }"
    , ".metric strong { font-size: 22px; }"
    , ".invoice-list, .timeline { display: grid; gap: 10px; margin: 16px 0 0; padding-left: 22px; }"
    , ".invoice-list li { padding: 8px 0; }"
    , ".invoice-list strong { margin-right: 10px; }"
    , ".agent-panel { display: grid; gap: 12px; margin-top: 16px; }"
    , ".global-agent-sidebar { position: sticky; top: 0; z-index: 2; display: grid; height: 100vh; height: 100dvh; min-height: 560px; border: 0; border-right: 1px solid rgba(23, 27, 34, 0.1); border-radius: 0; background: rgba(255, 255, 255, 0.96); box-shadow: none; overflow: visible; transition: background 160ms ease, border-color 160ms ease; }"
    , ".sidebar-tab { position: absolute; top: 50%; right: -19px; z-index: 5; display: inline-flex; align-items: center; justify-content: center; width: 20px; height: 62px; padding: 0; border: 1px solid rgba(23, 27, 34, 0.12); border-left: 0; border-radius: 0 999px 999px 0; background: rgba(255, 255, 255, 0.96); color: var(--runtime-accent); font: inherit; font-size: 22px; font-weight: 900; line-height: 1; cursor: pointer; transform: translateY(-50%); box-shadow: 6px 0 18px rgba(38, 48, 63, 0.08); }"
    , ".sidebar-tab:hover { background: #ffffff; color: #171b22; }"
    , ".app-container[data-sidebar-collapsed=\"true\"] .sidebar-tab { right: -25px; width: 26px; }"
    , ".app-container[data-sidebar-collapsed=\"true\"] .global-agent-sidebar { background: rgba(255, 255, 255, 0.72); }"
    , ".app-container[data-sidebar-collapsed=\"true\"] .sidebar-agent-panel { opacity: 0; pointer-events: none; transform: translateX(-10px); }"
    , ".sidebar-agent-panel { display: grid; grid-template-rows: minmax(0, 1fr) auto auto auto; min-height: 0; margin-top: 0; padding: 10px 10px max(10px, env(safe-area-inset-bottom)); overflow: hidden; }"
    , ".agent-status { display: none; }"
    , ".agent-log { display: flex; flex-direction: column; gap: 14px; min-height: 160px; max-height: 360px; overflow: auto; padding: 10px 2px 8px; background: transparent; }"
    , ".sidebar-agent-panel .agent-log { min-height: 0; max-height: none; }"
    , ".agent-event { display: grid; gap: 4px; max-width: min(680px, 100%); padding: 0; border-radius: 0; background: transparent; }"
    , ".agent-event.user { align-self: flex-end; max-width: 82%; padding: 10px 14px; border-radius: 14px; background: #1f1f1f; color: #ffffff; }"
    , ".agent-event.assistant { align-self: flex-start; max-width: 96%; }"
    , ".agent-event.tool { align-self: flex-start; max-width: 96%; padding: 7px 10px; border: 0; border-radius: 999px; background: rgba(53, 83, 91, 0.06); color: var(--runtime-accent); }"
    , ".agent-event.tool-strip { display: inline-flex; align-items: center; gap: 6px; width: fit-content; max-width: 100%; padding: 3px; border-radius: 9px; background: rgba(53, 83, 91, 0.06); }"
    , ".tool-icon { display: inline-flex; align-items: center; justify-content: center; width: 24px; height: 24px; border-radius: 7px; color: rgba(23, 27, 34, 0.34); }"
    , ".tool-icon svg { width: 14px; height: 14px; stroke: currentColor; stroke-width: 2.2; fill: none; stroke-linecap: round; stroke-linejoin: round; }"
    , ".tool-icon.is-active { color: var(--runtime-accent); background: rgba(53, 83, 91, 0.1); }"
    , ".agent-event small { display: none; }"
    , ".agent-event.tool small { display: inline; color: inherit; font-size: 11px; font-weight: 900; text-transform: uppercase; }"
    , ".agent-event p { margin: 0; max-width: none; color: inherit; font-size: 16px; line-height: 1.55; }"
    , ".agent-event.assistant p { color: #171b22; font-size: 17px; }"
    , ".agent-event.welcome p { font-size: 16px; color: #262b33; }"
    , ".agent-form { position: relative; display: block; }"
    , ".agent-form textarea { width: 100%; resize: none; min-height: 86px; padding: 14px 54px 14px 14px; border: 1px solid rgba(23, 27, 34, 0.14); border-radius: 14px; background: #ffffff; color: #171b22; font: inherit; font-size: 16px; line-height: 1.45; outline: none; box-shadow: inset 0 0 0 1px transparent; }"
    , ".agent-form textarea:focus { border-color: rgba(23, 27, 34, 0.28); box-shadow: 0 0 0 4px rgba(53, 83, 91, 0.08); }"
    , ".agent-form button { position: absolute; right: 10px; bottom: 10px; width: 36px; height: 36px; min-height: 0; padding: 0; border: 0; border-radius: 10px; background: var(--runtime-accent); color: #ffffff; font: inherit; font-size: 22px; font-weight: 800; line-height: 1; cursor: pointer; }"
    , ".agent-form button:disabled, .agent-form textarea:disabled { opacity: 0.62; cursor: wait; }"
    , ".agent-fragment-preview { min-height: 84px; padding: 10px; border: 1px solid rgba(23, 27, 34, 0.1); border-radius: 12px; background: rgba(246, 247, 245, 0.86); }"
    , ".agent-fragment-preview.is-empty { display: none; }"
    , ".sidebar-agent-panel .agent-fragment-preview { max-height: 220px; overflow: auto; }"
    , ".agent-fragment-preview .panel { margin-top: 8px; background: rgba(255, 255, 255, 0.72); }"
    , ".haskell-control-surface { display: grid; grid-template-columns: minmax(0, 1.3fr) minmax(220px, 0.7fr); gap: 12px; margin-top: 14px; }"
    , ".order-card, .agent-memory { padding: 14px; border: 1px solid #cfd8d7; border-radius: 8px; background: rgba(255, 255, 255, 0.58); }"
    , ".order-card h3, .agent-memory h3 { margin: 0 0 12px; font-size: 18px; }"
    , ".order-field { display: grid; grid-template-columns: 120px minmax(0, 1fr); align-items: center; gap: 10px; padding: 7px 0; }"
    , ".order-field span, .agent-memory span { color: #69737d; font-size: 13px; font-weight: 700; }"
    , ".order-field input { width: 100%; min-height: 34px; padding: 6px 8px; border: 1px solid #cfd8d7; border-radius: 7px; background: rgba(255, 255, 255, 0.86); color: #18212f; font: inherit; }"
    , ".agent-memory p { margin: 0 0 8px; max-width: none; font-size: 15px; }"
    , ".agent-memory ul { margin: 10px 0 0; padding-left: 18px; color: var(--runtime-accent); }"
    , ".agent-prompts { display: flex; flex-wrap: wrap; gap: 6px; padding: 8px 0; }"
    , ".agent-prompts button { min-height: 28px; padding: 0 9px; border: 0; border-radius: 8px; background: rgba(53, 83, 91, 0.08); color: var(--runtime-accent); font: inherit; font-size: 12px; font-weight: 800; cursor: pointer; }"
    , ".agent-prompts button:hover { background: rgba(53, 83, 91, 0.14); }"
    , "@media (max-width: 1100px) { .app-shell { grid-template-columns: 1fr; align-items: start; min-height: auto; } .app-container[data-sidebar-collapsed=\"true\"] .app-shell { grid-template-columns: 1fr; } .global-agent-sidebar { position: relative; top: auto; height: min(42vh, 360px); min-height: 280px; border-right: 0; border-bottom: 1px solid rgba(23, 27, 34, 0.1); box-shadow: none; overflow: visible; } .app-container[data-sidebar-collapsed=\"true\"] .global-agent-sidebar { height: 18px; min-height: 18px; } .sidebar-tab { top: auto; right: 50%; bottom: -22px; width: 62px; height: 23px; border: 1px solid rgba(23, 27, 34, 0.12); border-top: 0; border-radius: 0 0 999px 999px; transform: translateX(50%) rotate(90deg); box-shadow: 0 6px 18px rgba(38, 48, 63, 0.08); } .app-container[data-sidebar-collapsed=\"true\"] .sidebar-tab { right: 50%; bottom: -25px; width: 66px; } .sidebar-agent-panel .agent-log { max-height: none; } .topbar { padding: 0 14px; } .shell { width: min(100% - 24px, 980px); } }"
    , "@media (max-width: 920px) { .sandbox-workspace { grid-template-columns: 1fr; } .sandbox-side-panel { position: static; } .sandbox-page-wrap { min-height: 620px; padding: 34px 28px; } }"
    , "@media (max-width: 720px) { .haskell-control-surface, .sandbox-create { grid-template-columns: 1fr; } .sandbox-doc-toolbar { position: static; grid-template-columns: 1fr auto; } .sandbox-title-input, .sandbox-doc-toolbar .sandbox-doc-updated { grid-column: 1 / -1; } }"
    , "@media (max-width: 560px) { .shell { padding: 28px 0; } .sandbox-doc-shell { width: min(100% - 20px, 1220px); } .sandbox-page-wrap { padding: 24px 18px; } .facts div, .order-field { grid-template-columns: 1fr; gap: 6px; } }"
    ]

appScript :: String
appScript =
  intercalate
    "\n"
    [ "(() => {"
    , "  const container = document.querySelector('[data-page-container=\"client-factory\"]');"
    , "  if (!container || !window.fetch || !window.history) return;"
    , "  container.dataset.containerBootId = container.dataset.containerBootId || String(Date.now());"
    , ""
    , "  const isLocalLink = (link) => {"
    , "    if (!link || link.target || link.hasAttribute('download')) return false;"
    , "    const url = new URL(link.href, window.location.href);"
    , "    return url.origin === window.location.origin;"
    , "  };"
    , ""
    , "  const slotSelector = (target) => target ? `[data-fragment-slot=\"${target}\"]` : '[data-render-part]';"
    , ""
    , "  const waitForTransition = (element, fallbackMs) => new Promise((resolve) => {"
    , "    let done = false;"
    , "    const finish = () => {"
    , "      if (done) return;"
    , "      done = true;"
    , "      element.removeEventListener('transitionend', finish);"
    , "      resolve();"
    , "    };"
    , "    element.addEventListener('transitionend', finish, { once: true });"
    , "    window.setTimeout(finish, fallbackMs);"
    , "  });"
    , ""
    , "  const swapWithMist = async (currentPart, nextPart) => {"
    , "    currentPart.classList.add('fragment-fade-out');"
    , "    await waitForTransition(currentPart, 55);"
    , "    nextPart.classList.add('fragment-fade-in');"
    , "    currentPart.replaceWith(nextPart);"
    , "    nextPart.getBoundingClientRect();"
    , "    window.requestAnimationFrame(() => {"
    , "      nextPart.classList.add('fragment-fade-ready');"
    , "      nextPart.classList.remove('fragment-fade-in');"
    , "    });"
    , "    await waitForTransition(nextPart, 85);"
    , "    nextPart.classList.remove('fragment-fade-ready');"
    , "  };"
    , ""
    , "  const syncActiveTabs = (url) => {"
    , "    const path = new URL(url, window.location.href).pathname;"
    , "    container.querySelectorAll('[data-fragment-target]').forEach((link) => {"
    , "      const linkPath = new URL(link.href, window.location.href).pathname;"
    , "      link.classList.toggle('active', linkPath === path);"
    , "    });"
    , "  };"
    , ""
    , "  const setSidebarCollapsed = (collapsed) => {"
    , "    container.dataset.sidebarCollapsed = collapsed ? 'true' : 'false';"
    , "    container.querySelectorAll('[data-sidebar-toggle]').forEach((button) => {"
    , "      button.textContent = collapsed ? '›' : '‹';"
    , "      button.setAttribute('aria-label', collapsed ? 'Развернуть чат' : 'Свернуть чат');"
    , "      button.setAttribute('title', collapsed ? 'Развернуть чат' : 'Свернуть чат');"
    , "      button.setAttribute('aria-expanded', collapsed ? 'false' : 'true');"
    , "    });"
    , "    try { window.localStorage.setItem('cakebox.sidebarCollapsed', collapsed ? 'true' : 'false'); } catch (_) {}"
    , "  };"
    , ""
    , "  const initSidebarCollapse = () => {"
    , "    let collapsed = false;"
    , "    try { collapsed = window.localStorage.getItem('cakebox.sidebarCollapsed') === 'true'; } catch (_) {}"
    , "    setSidebarCollapsed(collapsed);"
    , "    container.querySelectorAll('[data-sidebar-toggle]').forEach((button) => {"
    , "      if (button.dataset.sidebarToggleConnected === 'true') return;"
    , "      button.dataset.sidebarToggleConnected = 'true';"
    , "      button.addEventListener('click', () => {"
    , "        setSidebarCollapsed(container.dataset.sidebarCollapsed !== 'true');"
    , "      });"
    , "    });"
    , "  };"
    , ""
    , "  const appendAgentEvent = (log, label, body, kind = '') => {"
    , "    const item = document.createElement('div');"
    , "    item.className = kind ? `agent-event ${kind}` : 'agent-event';"
    , "    const meta = document.createElement('small');"
    , "    meta.textContent = label;"
    , "    const text = document.createElement('p');"
    , "    text.textContent = body;"
    , "    item.append(meta, text);"
    , "    log.append(item);"
    , "    log.scrollTop = log.scrollHeight;"
    , "    return item;"
    , "  };"
    , ""
    , "  const iconSvg = (name) => {"
    , "    const icons = {"
    , "      start: '<path d=\"M14.7 6.3 17.7 3.3\"></path><path d=\"M15 3h3v3\"></path><path d=\"M4 20l6.8-6.8\"></path><path d=\"M11.5 12.5 8.8 9.8 13 5.6l2.7 2.7-4.2 4.2Z\"></path>',"
    , "      ui: '<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\"></rect><path d=\"M4 9h16\"></path><path d=\"M8 13h4\"></path>',"
    , "      state: '<ellipse cx=\"12\" cy=\"5\" rx=\"7\" ry=\"3\"></ellipse><path d=\"M5 5v10c0 1.7 3.1 3 7 3s7-1.3 7-3V5\"></path><path d=\"M5 10c0 1.7 3.1 3 7 3s7-1.3 7-3\"></path>',"
    , "      done: '<path d=\"M20 6 9 17l-5-5\"></path>'"
    , "    };"
    , "    return `<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\">${icons[name] || icons.start}</svg>`;"
    , "  };"
    , ""
    , "  const ensureToolStrip = (panel, log) => {"
    , "    if (panel._toolStrip?.isConnected) return panel._toolStrip;"
    , "    const item = document.createElement('div');"
    , "    item.className = 'agent-event tool-strip';"
    , "    [['start', 'tool started'], ['ui', 'UI action'], ['state', 'state updated'], ['done', 'tool finished']].forEach(([step, label]) => {"
    , "      const icon = document.createElement('span');"
    , "      icon.className = 'tool-icon';"
    , "      icon.dataset.toolStep = step;"
    , "      icon.title = label;"
    , "      icon.setAttribute('aria-label', label);"
    , "      icon.innerHTML = iconSvg(step);"
    , "      item.append(icon);"
    , "    });"
    , "    log.append(item);"
    , "    log.scrollTop = log.scrollHeight;"
    , "    panel._toolStrip = item;"
    , "    return item;"
    , "  };"
    , ""
    , "  const markToolStep = (panel, log, step) => {"
    , "    const strip = ensureToolStrip(panel, log);"
    , "    strip.querySelector(`[data-tool-step=\"${step}\"]`)?.classList.add('is-active');"
    , "    log.scrollTop = log.scrollHeight;"
    , "  };"
    , ""
    , "  const replaceFragmentFromEvent = async (event) => {"
    , "    if (event.name !== 'fragment.rendered' || !event.value?.target || !event.value?.html) return false;"
    , "    const template = document.createElement('template');"
    , "    template.innerHTML = event.value.html.trim();"
    , "    const selector = slotSelector(event.value.target);"
    , "    const nextPart = template.content.querySelector(selector);"
    , "    const currentPart = container.querySelector(selector);"
    , "    if (!nextPart || !currentPart) return false;"
    , "    await swapWithMist(currentPart, nextPart);"
    , "    syncActiveTabs(window.location.href);"
    , "    initAgentPanels(nextPart);"
    , "    initExtensionControls(nextPart);"
    , "    return true;"
    , "  };"
    , ""
    , "  const appendStateNote = (note) => {"
    , "    if (!note) return;"
    , "    const list = container.querySelector('[data-state-notes]');"
    , "    if (!list) return;"
    , "    if (list.children.length === 1 && list.textContent.includes('No state notes yet')) list.textContent = '';"
    , "    if (list.firstElementChild?.textContent === note) return;"
    , "    const item = document.createElement('li');"
    , "    item.textContent = note;"
    , "    list.prepend(item);"
    , "    while (list.children.length > 6) list.lastElementChild?.remove();"
    , "  };"
    , ""
    , "  const updateStatePanel = (value) => {"
    , "    if (!value) return;"
    , "    Object.entries(value).forEach(([key, nextValue]) => {"
    , "      if (nextValue === null || nextValue === undefined || key === 'note') return;"
    , "      const field = container.querySelector(`[data-state-field=\"${key}\"]`);"
    , "      if (field) field.textContent = String(nextValue);"
    , "    });"
    , "    appendStateNote(value.note);"
    , "  };"
    , ""
    , "  const applyUiAction = (value) => {"
    , "    if (!value?.action) return false;"
    , "    if (value.action === 'setThemeColor') {"
    , "      const color = value.themeColor || '#35535b';"
    , "      document.documentElement.style.setProperty('--runtime-accent', color);"
    , "      const themeField = container.querySelector('[data-state-field=\"preferredTheme\"]');"
    , "      if (themeField) themeField.textContent = color;"
    , "      return true;"
    , "    }"
    , "    if (value.action === 'updateOrderDraft') {"
    , "      Object.entries(value).forEach(([key, nextValue]) => {"
    , "        if (['action', 'note'].includes(key) || nextValue === null || nextValue === undefined) return;"
    , "        const input = container.querySelector(`[data-order-field=\"${key}\"]`);"
    , "        if (input) input.value = String(nextValue);"
    , "      });"
    , "      const lastOrder = container.querySelector('[data-state-field=\"lastOrderId\"]');"
    , "      const orderId = value.orderId || container.querySelector('[data-order-field=\"orderId\"]')?.value;"
    , "      if (lastOrder && orderId) lastOrder.textContent = orderId;"
    , "      return true;"
    , "    }"
    , "    if (value.action === 'navigate' && value.url) {"
    , "      renderFragment(value.url, true).catch(() => { window.location.href = value.url; });"
    , "      return true;"
    , "    }"
    , "    return false;"
    , "  };"
    , ""
    , "  const handleCustomEvent = async (event, markChanged) => {"
    , "    if (event.name === 'ui.action') {"
    , "      applyUiAction(event.value);"
    , "      if (markChanged) markChanged('ui');"
    , "      return;"
    , "    }"
    , "    if (event.name === 'state.updated') {"
    , "      updateStatePanel(event.value);"
    , "      if (markChanged) markChanged('state');"
    , "      return;"
    , "    }"
    , "    const changed = await replaceFragmentFromEvent(event);"
    , "    if (changed && markChanged) markChanged('ui');"
    , "  };"
    , ""
    , "  const handleAgentEvent = (panel, event) => {"
    , "    const log = panel.querySelector('[data-agent-log]');"
    , "    const status = panel.querySelector('[data-agent-status]');"
    , "    if (!log || !status) return;"
    , "    switch (event.type) {"
    , "      case 'RUN_STARTED':"
    , "        status.dataset.agentStatus = 'streaming';"
    , "        status.textContent = 'AI думает';"
    , "        break;"
    , "      case 'TEXT_MESSAGE_START':"
    , "        panel.dataset.currentAssistantId = event.messageId || 'assistant';"
    , "        panel._assistantRole = event.role || 'assistant';"
    , "        panel._assistantItem = null;"
    , "        break;"
    , "      case 'TEXT_MESSAGE_CONTENT':"
    , "        if (!event.delta) break;"
    , "        if (!panel._assistantItem) panel._assistantItem = appendAgentEvent(log, panel._assistantRole || 'assistant', '', 'assistant');"
    , "        panel._assistantItem.querySelector('p').textContent += event.delta || '';"
    , "        log.scrollTop = log.scrollHeight;"
    , "        break;"
    , "      case 'TEXT_MESSAGE_END':"
    , "        panel._assistantItem = null;"
    , "        status.dataset.agentStatus = 'idle';"
    , "        status.textContent = 'Готов к следующему сообщению';"
    , "        break;"
    , "      case 'TOOL_CALL_START':"
    , "        status.dataset.agentStatus = 'streaming';"
    , "        status.textContent = 'AI вызывает fragment tool';"
    , "        panel._toolStrip = null;"
    , "        markToolStep(panel, log, 'start');"
    , "        break;"
    , "      case 'TOOL_CALL_END':"
    , "        markToolStep(panel, log, 'done');"
    , "        break;"
    , "      case 'CUSTOM':"
    , "        handleCustomEvent(event, (step) => markToolStep(panel, log, step));"
    , "        break;"
    , "      case 'RUN_FINISHED':"
    , "        status.dataset.agentStatus = 'done';"
    , "        status.textContent = 'AI stream завершен';"
    , "        break;"
    , "      default:"
    , "        appendAgentEvent(log, event.type || 'event', JSON.stringify(event));"
    , "    }"
    , "  };"
    , ""
    , "  const readSseStream = async (response, onEvent) => {"
    , "    const reader = response.body.getReader();"
    , "    const decoder = new TextDecoder();"
    , "    let buffer = '';"
    , "    while (true) {"
    , "      const { value, done } = await reader.read();"
    , "      if (done) break;"
    , "      buffer += decoder.decode(value, { stream: true });"
    , "      const lines = buffer.split('\\n');"
    , "      buffer = lines.pop() || '';"
    , "      for (const line of lines) {"
    , "        const trimmed = line.trim();"
    , "        if (!trimmed.startsWith('data: ')) continue;"
    , "        const payload = trimmed.slice(6);"
    , "        if (payload === '[DONE]') continue;"
    , "        onEvent(JSON.parse(payload));"
    , "      }"
    , "    }"
    , "  };"
    , ""
    , "  const submitAgentMessage = async (panel, message) => {"
    , "    const log = panel.querySelector('[data-agent-log]');"
    , "    const status = panel.querySelector('[data-agent-status]');"
    , "    const url = panel.dataset.agentStreamUrl;"
    , "    const threadId = panel.dataset.agentThreadId || 'default-thread';"
    , "    if (!log || !status || !url) return;"
    , "    appendAgentEvent(log, 'user', message, 'user');"
    , "    status.dataset.agentStatus = 'streaming';"
    , "    status.textContent = 'Отправка в AI';"
    , "    const response = await fetch(url, {"
    , "      method: 'POST',"
    , "      headers: { 'Content-Type': 'application/json' },"
    , "      body: JSON.stringify({"
    , "        threadId,"
    , "        runId: `run_${Date.now()}`," 
    , "        messages: [{ role: 'user', content: message }]"
    , "      })"
    , "    });"
    , "    if (!response.ok || !response.body) throw new Error(`AI request failed: ${response.status}`);"
    , "    await readSseStream(response, (event) => handleAgentEvent(panel, event));"
    , "  };"
    , ""
    , "  const initAgentPanels = (root = container) => {"
    , "    root.querySelectorAll('[data-agent-panel]').forEach((panel) => {"
    , "      if (panel.dataset.agentConnected === 'true') return;"
    , "      const status = panel.querySelector('[data-agent-status]');"
    , "      const form = panel.querySelector('[data-agent-form]');"
    , "      if (!form || !status) return;"
    , "      panel.dataset.agentConnected = 'true';"
    , "      status.dataset.agentStatus = 'idle';"
    , "      status.textContent = 'Готов к сообщению';"
    , "      const input = form.elements.message;"
    , "      input.addEventListener('keydown', (event) => {"
    , "        if (event.key !== 'Enter' || event.shiftKey || event.altKey) return;"
    , "        if (!event.metaKey && !event.ctrlKey) return;"
    , "        event.preventDefault();"
    , "        form.requestSubmit();"
    , "      });"
    , "      form.addEventListener('submit', async (event) => {"
    , "        event.preventDefault();"
    , "        const message = input.value.trim();"
    , "        if (!message) return;"
    , "        input.value = '';"
    , "        input.disabled = true;"
    , "        form.querySelector('button')?.setAttribute('disabled', 'disabled');"
    , "        try {"
    , "          await submitAgentMessage(panel, message);"
    , "        } catch (error) {"
    , "          status.dataset.agentStatus = 'error';"
    , "          status.textContent = 'AI stream недоступен';"
    , "          const log = panel.querySelector('[data-agent-log]');"
    , "          if (log) appendAgentEvent(log, 'error', error.message || String(error));"
    , "        } finally {"
    , "          input.disabled = false;"
    , "          form.querySelector('button')?.removeAttribute('disabled');"
    , "          input.focus();"
    , "        }"
    , "      });"
    , "      panel.querySelectorAll('[data-agent-prompt]').forEach((button) => {"
    , "        button.addEventListener('click', () => {"
    , "          const input = form.elements.message;"
    , "          input.value = button.dataset.agentPrompt || '';"
    , "          form.requestSubmit();"
    , "        });"
    , "      });"
    , "    });"
    , "  };"
    , ""
    , "  const runExtensionAction = async (action, argumentsValue = {}) => {"
    , "    container.dataset.loading = 'true';"
    , "    container.dataset.loadingTarget = 'extension-action';"
    , "    try {"
    , "      const response = await fetch('/extensions/actions', {"
    , "        method: 'POST',"
    , "        headers: { 'Content-Type': 'application/json' },"
    , "        body: JSON.stringify({ action, arguments: argumentsValue })"
    , "      });"
    , "      const payload = await response.json();"
    , "      if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.content || `Action failed: ${response.status}`);"
    , "      for (const event of payload.events || []) await handleCustomEvent(event);"
    , "      return payload;"
    , "    } finally {"
    , "      container.dataset.loading = 'false';"
    , "      delete container.dataset.loadingTarget;"
    , "    }"
    , "  };"
    , ""
    , "  const initExtensionControls = (root = container) => {"
    , "    root.querySelectorAll('[data-extension-action-form]').forEach((form) => {"
    , "      if (form.dataset.extensionConnected === 'true') return;"
    , "      form.dataset.extensionConnected = 'true';"
    , "      form.addEventListener('submit', async (event) => {"
    , "        event.preventDefault();"
    , "        const action = form.dataset.extensionActionForm;"
    , "        const data = new FormData(form);"
    , "        const args = Object.fromEntries(data.entries());"
    , "        try {"
    , "          await runExtensionAction(action, args);"
    , "          form.reset();"
    , "        } catch (error) {"
    , "          console.error(error);"
    , "        }"
    , "      });"
    , "    });"
    , "    root.querySelectorAll('[data-extension-action]').forEach((button) => {"
    , "      if (button.dataset.extensionConnected === 'true') return;"
    , "      button.dataset.extensionConnected = 'true';"
    , "      button.addEventListener('click', async () => {"
    , "        const action = button.dataset.extensionAction;"
    , "        const args = {};"
    , "        if (button.dataset.symbol) args.symbol = button.dataset.symbol;"
    , "        try {"
    , "          await runExtensionAction(action, args);"
    , "        } catch (error) {"
    , "          console.error(error);"
    , "        }"
    , "      });"
    , "    });"
    , "  };"
    , ""
    , "  const renderFragment = async (url, push, target) => {"
    , "    container.dataset.loading = 'true';"
    , "    container.dataset.loadingTarget = target || 'page';"
    , "    try {"
    , "      const headers = {"
    , "        'X-Render-Mode': 'fragment',"
    , "        'X-Requested-With': 'container'"
    , "      };"
    , "      if (target) headers['X-Render-Target'] = target;"
    , "      const response = await fetch(url, {"
    , "        headers"
    , "      });"
    , "      if (!response.ok) throw new Error(`Fragment request failed: ${response.status}`);"
    , "      const html = await response.text();"
    , "      const template = document.createElement('template');"
    , "      template.innerHTML = html.trim();"
    , "      const selector = slotSelector(target);"
    , "      const nextPart = template.content.querySelector(selector);"
    , "      const currentPart = container.querySelector(selector);"
    , "      if (!nextPart || !currentPart) {"
    , "        window.location.href = url;"
    , "        return;"
    , "      }"
    , "      await swapWithMist(currentPart, nextPart);"
    , "      if (push) window.history.pushState({}, '', url);"
    , "      if (target) syncActiveTabs(url);"
    , "      initAgentPanels(nextPart);"
    , "      initExtensionControls(nextPart);"
    , "      document.title = nextPart.querySelector('h1')?.textContent || document.querySelector('h1')?.textContent || 'Cakebox';"
    , "      if (!target) window.scrollTo({ top: 0, behavior: 'instant' });"
    , "    } finally {"
    , "      container.dataset.loading = 'false';"
    , "      delete container.dataset.loadingTarget;"
    , "    }"
    , "  };"
    , ""
    , "  document.addEventListener('click', (event) => {"
    , "    const link = event.target.closest('a[href]');"
    , "    if (!isLocalLink(link) || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;"
    , "    event.preventDefault();"
    , "    renderFragment(link.href, true, link.dataset.fragmentTarget).catch(() => { window.location.href = link.href; });"
    , "  });"
    , ""
    , "  window.addEventListener('popstate', () => {"
    , "    renderFragment(window.location.href, false).catch(() => window.location.reload());"
    , "  });"
    , ""
    , "  initSidebarCollapse();"
    , "  initAgentPanels();"
    , "  initExtensionControls();"
    , "})();"
    ]
